default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

development:
  <<: *default
  database: start_kit_development

test:
  <<: *default
  database: start_kit_test

production:
  <<: *default
  database: start_kit_production
  username: start_kit
  password: <%= ENV["START_KIT_DATABASE_PASSWORD"] %>
